---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: 您可以建立、修改、刪除備份資源群組，以及對資源群組進行備份作業。 
---
= 管理資源組
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以建立、修改、刪除備份資源群組，以及對資源群組進行備份作業。


NOTE: 資源群組在虛擬儲存控制台 (VSC) 中稱為備份作業。



[[suspend-and-resume-operations-on-resource-groups]]
== 暫停和恢復資源組的操作

您可以暫時禁止在資源組上啟動計劃操作。稍後當您需要時，您可以啟用這些操作。

.步驟
. 在 SCV 外掛程式的左側導覽窗格中，選擇 *資源組*，選擇資源組並選擇 *暫停*（或選擇 *復原*）。
. 在確認框中，選擇*OK*進行確認。


.完成後
在「資源組」頁面上，暫停資源的作業狀態為 `Under_Maintenance`。您可能需要捲動到表格右側才能看到「作業狀態」列。

恢復備份作業後，作業狀態將變更為 `Production`。



[[modify-resource-groups]]
== 修改資源組

您可以在 vCenter 中的資源組中刪除或新增資源、分離或附加策略、修改計劃或修改任何其他資源組選項。

.關於此任務
如果要修改資源組的名稱，請不要在虛擬機器、資料儲存區、政策、備份或資源組名稱中使用以下特殊字元：

% & * $ # @ ！\ / ： * ？“ < > - | ; ' ，以及空格。允許使用底線字元 (_)。

.步驟
. 在 SCV 外掛程式的左側導覽窗格中，選擇 *資源組*，然後選擇資源組並選擇 *編輯*。
. 在「編輯資源組」精靈的左側清單中，選擇要修改的類別並輸入您的變更。
+
您可以在多個類別中進行變更。您也可以在此選項中編輯二級受保護資源。

. 選擇“*下一步*”，直到看到“摘要”頁面，然後選擇“*完成*”。




[[delete-resource-groups]]
== 刪除資源組

如果不再需要保護資源組中的資源，則可以在 vCenter 中刪除該資源組。在從 vCenter 中刪除SnapCenter Plug-in for VMware vSphere之前，必須確保刪除所有資源組。

.關於此任務
所有資源組刪除操作均以強制刪除的方式執行。刪除作業會從 vCenter 資源組中分離所有原則、從SnapCenter Plug-in for VMware vSphere中刪除資源組，並刪除資源組的所有備份和快照。


NOTE: 在SnapVault關係中，無法刪除最後一個快照；因此，無法刪除資源組。在刪除屬於SnapVault關係的資源群組之前，您必須使用 System Manager 或使用ONTAP CLI 刪除SnapVault關係，然後必須刪除最後一個快照。

.步驟
. 在 SCV 外掛程式的左側導覽窗格中，選擇 *資源組*，然後選擇資源組並選擇 *刪除*。
. 在*刪除資源組*確認框中，選擇*確定*進行確認。

