---
sidebar: sidebar 
permalink: scpivs44_view_status_information.html 
keywords:  
summary: 您可以在 vSphere 用戶端儀表板上查看狀態資訊。狀態資訊每小時更新一次。 
---
= 查看狀態資訊
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在 vSphere 用戶端儀表板上查看狀態資訊。狀態資訊每小時更新一次。

.步驟
. 從 vCenter 用戶端捷徑頁面中，選擇SnapCenter Plug-in for VMware vSphere。
. 在 SCV 的左側導覽窗格中，選擇 *儀表板* > *狀態*。
. 查看概覽狀態資訊或選擇連結以獲取更多詳細信息，如下表所列。
+
|===
| 此儀表板磁貼... | 顯示以下資訊... 


 a| 
最近的工作活動
 a| 
最近三到五次備份、還原和裝載作業。

** 選擇工作 ID 即可查看有關該工作的更多詳細資訊。
** 選擇“查看全部”轉到“作業監視器”選項卡，查看所有作業的更多詳細資訊。




 a| 
工作
 a| 
在選定的時間視窗內執行的每種作業類型（備份、還原和裝載）的計數。將遊標停留在圖表的某個部分上可以查看該類別的更多詳細資訊。



 a| 
最新保護摘要
 a| 
選定時間窗口內主虛擬機器和輔助虛擬機器或資料儲存區的資料保護狀態摘要。

** 選擇下拉式選單以選擇*VMs*或*Datastores*。
** 對於二級存儲，選擇 * SnapVault* 或 * SnapMirror*。
** 將遊標停留在圖表的某個部分上，即可查看該類別中的虛擬機器或資料儲存的數量。在「成功」類別中，列出了每個資源的最新備份。
** 您可以透過編輯設定檔來變更時間視窗。預設值為 7 天。有關詳細信息，請參閱link:scpivs44_customize_your_configuration.html["自訂您的配置"] 。
** 每次主備份或輔助備份後都會更新內部計數器。儀表板磁貼每六小時刷新一次。刷新時間無法變更。注意：如果您使用鏡像保管庫保護策略，則保護摘要的計數器將顯示在SnapVault摘要圖表中，而不是SnapMirror圖表中。




 a| 
配置
 a| 
SnapCenter Plug-in for VMware vSphere管理的每種類型物件的總數。



 a| 
儲存
 a| 
產生的快照、 SnapVault和SnapMirror快照的總數以及用於主快照和二級快照的儲存量。此折線圖分別繪製了連續 90 天期間每天的主儲存和二級儲存消耗。儲存資訊每 24 小時凌晨 1:08 更新一次儲存節省是邏輯容量（快照節省加上消耗的儲存）與主儲存的實體容量的比率。長條圖顯示了儲存節省情況。

將遊標停留在圖表上的某條線上即可查看每日的詳細結果。

|===

