---
sidebar: sidebar 
permalink: scpivs44_properties_you_can_override.html 
keywords:  
summary: '您可以使用 `scbr.override`配置檔案來更改預設值。' 
---
= 可以覆蓋的屬性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用 `scbr.override`配置檔案來更改預設值。

* 預設情況下，模板使用井號來註解配置屬性。若要使用屬性修改配置值，必須刪除 `#`人物。
* 您必須重新啟動SnapCenter Plug-in for VMware vSphere上的服務才能使變更生效。


您可以使用 `scbr.override`配置檔案來更改預設值。

* *儀表板.受保護.虛擬機器.計數.間隔=7*
+
指定儀表板顯示虛擬機器保護狀態的天數。

+
預設值為“7”。

* *停用.weakCiphers=true*
+
停用適用於SnapCenter Plug-in for VMware vSphere與SnapCenter之間的通訊通道的以下弱密碼，以及 `include.weakCiphers`：TLS_RSA_使用_AES_256_CBC_SHA256 TLS_DHE_RSA_使用_AES_256_CBC_SHA256 TLS_RSA_使用_AES_128_CBC_SHA256 TLS_DHE_RSA_使用_AES_128_128_CBC_SHA256 TLS_DHE_RSA_使用_AES_128_128_CBC_SHA256 TLS_DHE_RSA_使用_AES_128_CBC_SHA256_RSA_ECS8 TLS_ECDHE_RSA_使用_AES_128_CBC_SHA256 TLS_RSA_使用_AES_128_GCM_SHA256 TLS_RSA_使用_AES_256_GCM_SHA384

* *全域.ds.排除.模式*
+
指定要從備份作業中排除的一個或多個傳統資料儲存區或 vVol 資料儲存區。您可以使用任何有效的 Java 正規表示式指定資料儲存。

+
例 1：表達式 `global.ds.exclusion.pattern=.*21`排除具有共同模式的資料儲存；例如 `datastore21`和 `dstest21`將被排除。

+
例 2：表達式 `global.ds.exclusion.pattern=ds-.*|^vol123`排除所有包含 `ds-`（例如 `scvds-test`）或以 `vol123`。

* *guestFileRestore.guest.operation.interval=5*
+
指定適用SnapCenter Plug-in for VMware vSphere監控來賓作業系統上來賓操作（線上磁碟和還原檔案）完成情況的時間間隔（以秒為單位）。總等待時間由 `guestFileRestore.online.disk.timeout`和 `guestFileRestore.restore.files.timeout`。

+
預設值為“5”。

* *guestFileRestore.monitorInterval=30*
+
指定SnapCenter Plug-in for VMware vSphere監控過期客戶機檔案還原工作階段的時間間隔（以分鐘為單位）。任何超出配置的會話時間運行的會話都會中斷。

+
預設值為“30”。

* *guestFileRestore.online.disk.timeout=100*
+
指定SnapCenter Plug-in for VMware vSphere等待來賓虛擬機器上的線上磁碟作業完成的時間（以秒為單位）。請注意，在插件輪詢線上磁碟操作完成之前，還需要等待 30 秒。

+
預設值為“100”。

* *guestFileRestore.restore.files.timeout=3600*
+
指定SnapCenter Plug-in for VMware vSphere等待來賓虛擬機器上的還原檔案作業完成的時間（以秒為單位）。如果超過時間，則該過程將結束，並且該作業將被標記為失敗。

+
預設值為“3600”（1小時）。

* *guestFileRestore.robocopy.directory.flags=/R:0 /W:0 /ZB /CopyAll /EFSRAW /A-:SH /e /NJH /NDL /NP*
+
指定在來賓檔案復原作業期間複製目錄時所使用的額外 robocopy 標誌。

+
不要刪除 `/NJH`或添加 `/NJS`因為這會破壞恢復輸出的解析。

+
不允許無限次重試（透過刪除 `/R`標誌），因為這可能會導致失敗的複製無休止地重試。

+
預設值為 `"/R:0 /W:0 /ZB /CopyAll /EFSRAW /A-:SH /e /NJH /NDL /NP"`。

* *guestFileRestore.robocopy.file.flags=/R:0 /W:0 /ZB /CopyAll /EFSRAW /A-:SH /NJH /NDL /NP*
+
指定在來賓檔案還原作業期間複製單一檔案時要使用的額外 robocopy 標誌。

+
不要刪除 `/NJH`或添加 `/NJS`因為這會破壞恢復輸出的解析。

+
不允許無限次重試（透過刪除 `/R`標誌），因為這可能會導致失敗的複製無休止地重試。

+
預設值為 `"/R:0 /W:0 /ZB /CopyAll /EFSRAW /A-:SH /NJH /NDL /NP"`。

* *guestFileRestore.sessionTime=1440*
+
指定適用SnapCenter Plug-in for VMware vSphere保持客戶檔案還原工作階段處於活動狀態的時間（以分鐘為單位）。

+
預設值為“1440”（24 小時）。

* *guestFileRestore.使用.自訂.線上.磁碟.腳本=true*
+
指定在建立來賓檔案還原工作階段時是否使用自訂腳本來聯機磁碟並擷取磁碟機號碼。該腳本必須位於 `[Install Path]  \etc\guestFileRestore_onlineDisk.ps1`。安裝時會提供預設腳本。價值觀 `[Disk_Serial_Number]`， `[Online_Disk_Output]` ， 和 `[Drive_Output]`在附加過程中在腳本中被替換。

+
預設值為“false”。

* *包括.esx.啟動器.id.來自.集群=真*
+
指定適用SnapCenter Plug-in for VMware vSphere應在透過 VMDK 工作流程的應用程式中包含來自叢集中所有 ESXi 主機的 iSCSI 和 FCP 啟動器 ID。

+
預設值為“false”。

* *包括.弱密碼*
+
什麼時候 `disable.weakCiphers`設定為 `true`，除了指定要停用的弱密碼外，還指定 `disable.weakCiphers`預設禁用。

* *最大並發數=15*
+
指定適用SnapCenter Plug-in for VMware vSphere可以向SnapCenter伺服器發出的最大並發呼叫數，以發現資料儲存區的儲存空間。當您在SnapCenter Plug-in for VMware vSphere上重新啟動 Linux 服務時，外掛程式會進行這些呼叫。

* *nfs.datastore.mount.重試.計數=3*
+
指定SnapCenter Plug-in for VMware vSphere嘗試在 vCenter 中將磁碟區作為 NFS 資料儲存區掛載的最大次數。

+
預設值為“3”。

* *nfs.datastore.mount.重試.延遲=60000*
+
指定SnapCenter Plug-in for VMware vSphere在 vCenter 中嘗試將磁碟區掛載為 NFS 資料儲存區之間等待的時間（以毫秒為單位）。

+
預設值為“60000”（60 秒）。

* *script.virtual.machine.count.variable.name=虛擬機器*
+
指定包含虛擬機器數量的環境變數名稱。在備份作業期間執行任何使用者定義的腳本之前，必須定義變數。

+
例如，VIRTUAL_MACHINES=2 表示正在備份兩台虛擬機器。

* *script.virtual.machine.info.variable.name=虛擬機器.%s*
+
提供包含備份中第 n 個虛擬機器的資訊的環境變數的名稱。在備份期間執行任何使用者定義的腳本之前，必須設定此變數。

+
例如，環境變數 VIRTUAL_MACHINE.2 提供有關備份中第二台虛擬機器的資訊。

* *script.virtual.machine.info.format= %s|%s|%s|%s|%s*
+
提供有關虛擬機器的資訊。此資訊的格式在環境變數中設置，如下所示： `VM name|VM UUID| VM power state (on|off)|VM snapshot taken (true|false)|IP address(es)`

+
以下是您可能提供的資訊的範例：

+
`VIRTUAL_MACHINE.2=VM 1|564d6769-f07d-6e3b-68b1f3c29ba03a9a|POWERED_ON||true|10.0.4.2`

* *儲存.連接.逾時=600000*
+
指定SnapCenter伺服器等待儲存系統回應的時間（以毫秒為單位）。

+
預設值為“600000”（10分鐘）。

* *vmware.esx.ip.kernel.ip.映射*
+
沒有預設值。使用此值將 ESXi 主機 IP 位址對應到 VMkernel IP 位址。預設情況下，適用SnapCenter Plug-in for VMware vSphere使用 ESXi 主機的管理 VMkernel 適配器 IP 位址。如果您希望SnapCenter Plug-in for VMware vSphere使用不同的 VMkernel 適配器 IP 位址，則必須提供覆蓋值。

+
在下列範例中，管理 VMkernel 適配器 IP 位址為 10.225.10.56；但是，SnapCenter Plug-in for VMware vSphere使用指定的位址 10.225.11.57 和 10.225.11.58。如果管理 VMkernel 適配器 IP 位址為 10.225.10.60，則插件使用位址 10.225.11.61。

+
`vmware.esx.ip.kernel.ip.map=10.225.10.56:10.225.11.57,10.225.11.58; 10.225.10.60:10.225.11.61`

* *vmware.max.concurrent.snapshots=30*
+
指定SnapCenter Plug-in for VMware vSphere在伺服器上執行的並發 VMware 快照的最大數量。

+
此數字是根據每個資料儲存進行檢查的，並且僅在策略選擇了「VM 一致」時才進行檢查。如果您正在執行崩潰一致性備份，則此設定不適用。

+
預設值為“30”。

* *vmware.max.concurrent.snapshots.delete=30*
+
指定適用SnapCenter Plug-in for VMware vSphere在伺服器上執行的每個資料儲存區的最大並發 VMware 快照刪除操作數。

+
此數字是根據每個資料儲存區進行檢查的。

+
預設值為“30”。

* *vmware.query.unresolved.retry.count=10*
+
指定SnapCenter Plug-in for VMware vSphere因「... 延遲 I/O 的時間限制...」錯誤而重試傳送有關未解析磁碟區的查詢的最大次數。

+
預設值為“10”。

* *vmware.quiesce.retry.count=0*
+
指定SnapCenter Plug-in for VMware vSphere在備份期間因「... 延遲 I/O 的時間限制...」錯誤而重試傳送有關 VMware 快照的查詢的最大次數。

+
預設值為“0”。

* *vmware.quiesce.retry.interval=5*
+
指定SnapCenter Plug-in for VMware vSphere在備份期間傳送有關 VMware 快照「... 延遲 I/O 的時間限制...」錯誤的查詢之間等待的時間（以秒為單位）。

+
預設值為“5”。

* *vmware.query.unresolved.retry.delay=60000*
+
指定SnapCenter Plug-in for VMware vSphere在傳送有關未解析磁碟區的查詢之間等待的時間（以毫秒為單位），因為出現「... 延遲 I/O 的時間限制...」錯誤。克隆 VMFS 資料儲存時發生此錯誤。

+
預設值為“60000”（60 秒）。

* *vmware.reconfig.vm.重試.計數=10*
+
指定SnapCenter Plug-in for VMware vSphere因「... 延遲 I/O 的時間限制...」錯誤而重試傳送重新配置虛擬機器的查詢的最大次數。

+
預設值為“10”。

* *vmware.reconfig.vm.retry.delay=30000*
+
指定SnapCenter Plug-in for VMware vSphere在傳送有關重新配置虛擬機器的查詢之間等待的最長時間（以毫秒為單位），因為「... 延遲 I/O 的時間限制...」錯誤。

+
預設值為“30000”（30秒）。

* *vmware.rescan.hba.重試.計數=3*
+
指定SnapCenter Plug-in for VMware vSphere在傳送有關重新掃描主機匯流排適配器的查詢之間等待的時間（以毫秒為單位），因為出現「... 延遲 I/O 的時間限制...」錯誤。

+
預設值為“3”。

* *vmware.rescan.hba.重試.延遲=30000*
+
指定SnapCenter Plug-in for VMware vSphere重試重新掃描主機匯流排適配器的請求的最大次數。

+
預設值為“30000”。


