---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_from_vmdks.html 
keywords:  
summary: 您可以從 Windows 用戶作業系統上的 VMDK 還原一個或多個檔案或資料夾。 
---
= 從 VMDK 還原客戶機檔案和資料夾
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以從 Windows 用戶作業系統上的 VMDK 還原一個或多個檔案或資料夾。

.關於此任務
預設情況下，附加的虛擬磁碟可用 24 小時，然後自動分離。您可以在精靈中選擇在還原作業完成時自動刪除會話，也可以隨時手動刪除來賓檔案還原會話，或在*來賓設定*頁面中延長時間。

來賓檔案或資料夾恢復效能取決於兩個因素：正在復原的檔案或資料夾的大小；以及正在復原的檔案或資料夾的數量。如果要恢復的資料集大小相同，則恢復大量小檔案可能比恢復少量大檔案花費的時間比預期的要長。


IMPORTANT: 一台虛擬機器上同時只能執行一個連線或還原操作。您無法在同一台虛擬機器上執行並行連線或復原操作。


IMPORTANT: 訪客恢復功能可讓您查看和恢復系統和隱藏檔案以及查看加密檔案。不要嘗試覆蓋現有的系統檔案或將加密檔案還原到加密資料夾。在復原操作期間，客戶檔案的隱藏、系統和加密屬性不會保留在復原的檔案中。查看或瀏覽保留分割區可能會導致錯誤。

.步驟
. 從 vSphere 用戶端捷徑視窗中，選擇「*主機和叢集*」並選擇一個 VM。
. 右鍵點選虛擬機器並選擇 * SnapCenter Plug-in for VMware vSphere* > *Guest File Restore*。
. 在「*復原範圍*」頁面上，透過執行下列操作指定包含要附加的虛擬磁碟的備份：
+
.. 在「*備份名稱*」表中，選擇包含要附加的虛擬磁碟的備份。
.. 在 *VMDK* 表中，選擇包含要還原的檔案或資料夾的虛擬磁碟。
.. 在「*位置*」表中，選擇要附加的虛擬磁碟的位置（主位置或輔助位置）。


. 在*客人詳情*頁面上，執行以下操作。
+
.. 選擇虛擬磁碟的連線位置：
+
|===
| 選擇此選項... | 如果… 


| 使用來賓虛擬機  a| 
您需要將虛擬磁碟附加到啟動精靈之前右鍵單擊的 VM，然後選擇右鍵單擊的 VM 的憑證。


NOTE: 必須已經為虛擬機器建立憑證。



| 使用客戶文件恢復代理虛擬機  a| 
您想要將虛擬磁碟附加到代理虛擬機，然後選擇代理虛擬機。


NOTE: 必須在連線和復原作業開始之前設定代理虛擬機器。

|===
.. 選擇*發送電子郵件通知*選項。
+
如果您希望在連線作業完成且虛擬磁碟可用時收到通知，則需要此選項。通知電子郵件包括虛擬磁碟名稱、虛擬機器名稱以及 VMDK 新指派的磁碟機號碼。

+

TIP: 啟用此選項是因為來賓檔案復原是非同步操作，並且可能需要一些時間才能為您建立來賓工作階段。

+
此選項使用在 vCenter 中設定 VMware vSphere 用戶端時配置的電子郵件設定。



. 查看摘要，然後選擇*完成*。
+
在選擇「*完成*」之前，您可以返回精靈中的任意頁面並變更資訊。

. 等待附加操作完成。
+
您可以在 Dashboard 作業監視器中查看操作的進度，也可以等待電子郵件通知。

. 若要尋找要從附加虛擬磁碟還原的文件，請從SnapCenter Plug-in for VMware vSphere in for VMware vSphere *。
. 在左側導覽窗格中選擇“*Guest File Restore*”>“*Guest Configuration*”。
+
在來賓會話監控表中，您可以透過選擇 *... 顯示有關會話的其他資訊。  *在右欄。

. 選擇通知電子郵件中列出的虛擬磁碟的客戶檔案還原工作階段。
+
所有分割區都分配有一個磁碟機號，包括系統保留分割區。如果 VMDK 有多個分割區，您可以透過在用戶端檔案瀏覽頁面頂部的磁碟機欄位中的下拉清單中選擇磁碟機來選擇特定的磁碟機。

. 選擇*瀏覽檔案*圖示以查看虛擬磁碟上的檔案和資料夾清單。
+
當您雙擊資料夾來瀏覽並選擇單一檔案時，取得檔案清單時可能會有時間延遲，因為取得操作是在執行時執行的。

+
為了更方便地瀏覽，您可以在搜尋字串中使用過濾器。過濾器區分大小寫，Perl 表達式中沒有空格。預設搜尋字串是 `.`*.下表顯示了一些 Perl 搜尋表達式的範例。

+
|===
| 這個表情… | 搜尋… 


| 。 | 除換行符之外的任何字元。 


| .* | 任何字串。這是預設值。 


| 一個 | 字符 a。 


| ab | 字串 ab。 


| a [豎線] b | 字元 a 或 b。 


| 一個* | 字元 a 的零個或多個實例。 


| a+ | 字元 a 的一個或多個實例。 


| 一個？ | 字元 a 的零個或一個實例。 


| 斧頭} | 字元 a 剛好有 x 個實例。 


| 斧頭，} | 字元 a 至少有 x 個實例。 


| a{x,y} | 字元 a 的實例至少有 x 個，最多有 y 個。 


| \ | 轉義特殊字元。 
|===
+
訪客文件瀏覽頁面除了顯示所有其他文件和資料夾外，還顯示所有隱藏文件和資料夾。

. 選擇一個或多個要還原的檔案或資料夾，然後選擇「選擇還原位置」。
+
要復原的檔案和資料夾列在「選​​定檔案」表中。

. 在「選擇復原位置」頁面中，指定以下內容：
+
|===
| 選項 | 描述 


| 恢復路徑 | 輸入將復原所選檔案的來賓的 UNC 共用路徑。  IPv4 位址範例： `\\10.60.136.65\c$` IPv6位址範例： `\\fd20-8b1e-b255-832e--61.ipv6-literal.net\C\restore` 


| 如果原始文件存在  a| 
如果要還原的檔案或資料夾已存在於還原目標中，請選擇要採取的動作：始終覆寫或始終跳過。


NOTE: 如果該資料夾已經存在，則該資料夾的內容將與現有資料夾合併。



| 恢復成功後斷開訪客會話 | 如果您希望在復原作業完成時刪除來賓檔案復原會話，請選擇此選項。 
|===
. 選擇*恢復*。
+
您可以在儀表板作業監視器中查看還原操作的進度，也可以等待電子郵件通知。發送電子郵件通知所需的時間取決於恢復操作完成所需的時間長度。

+
通知電子郵件包含一個附件，其中包含恢復操作的輸出。如果恢復操作失敗，請開啟附件以取得更多資訊。


