---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__mount_and_unmount_datastores.html 
keywords:  
summary: 若要使用適用SnapCenter Plug-in for VMware vSphere對資料儲存區備份執行掛載和卸載作業，必須遵循規定的 REST API 呼叫順序。 
---
= 用於掛載和卸載資料儲存的 REST API 工作流程
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要使用適用SnapCenter Plug-in for VMware vSphere對資料儲存區備份執行掛載和卸載作業，必須遵循規定的 REST API 呼叫順序。

對於每個 REST API，新增 `\https://<server>:<port>`在 REST API 的前面形成一個完整的端點。



[[to-mount-datastores-follow-this-workflow]]
== 若要掛載資料存儲，請遵循以下工作流程：

|===
| 步 | REST API | 評論 


| 1 | 前往 `\http://<vCenter-IP>/mob` | 從 VMware 管理物件 URL 中尋找資料儲存 moref。請注意您要掛載的資料儲存的 *moref*。 


| 2 | `/4.1/datastores/{moref}/
backups` | `Get the list of backups for a datastore`取得指定資料儲存的備份清單。傳遞步驟 1 中的 *moref*。記下您想要掛載的 *backupId*。 


| 3 | `/4.1/datastores/backups/
{backupId}/snapshotlocators` | `Get the list of Snapshot Locations`取得有關指定備份位置的詳細資訊。傳遞步驟 2 中的 *backupId*。注意 *datastore* 和 *snapshotLocationsList* 清單中的位置。 


| 4 | `/4.1/datastores/{moref}/
availableEsxHosts` | `Get the list of Available Esxi Hosts`取得可用於掛載操作的 ESXi 主機清單。傳遞步驟 1 中的 *moref*。注意*availableEsxHostsList*訊息。 


| 5 | `/4.1/datastores/backups/
{backupId}/mount` | `Mount datastores for a backup`掛載指定的資料儲存備份。傳遞步驟 2 中的 *backupId*。在 *datastore* 和 *location* 屬性中，傳遞來自 `snapshotLocationsList`在步驟 3 中。在 *esxHostName* 屬性中，傳遞步驟 4 中 *availableEsxHostsList* 的資訊。 
|===


[[to-unmount-datastores-follow-this-workflow]]
== 要卸載資料存儲，請遵循以下工作流程：

|===
| 步 | REST API | 評論 


| 1 | `/4.1/datastores/backups/
{backupId}/mounted` | `Get the list of mounted datastores` 。請注意您想要卸載的資料儲存*moref*。 


| 2 | `/4.1/datastores/unmount` | `UnMount datastores for a backup`卸載指定的資料儲存備份。傳遞步驟 1 中的資料儲存 *moref*(s)。 
|===