---
sidebar: sidebar 
permalink: scpivs44_mount_a_backup.html 
keywords:  
summary: 如果您想存取備份中的文件，您可以從備份中掛載傳統資料儲存。您可以將備份掛載到已建立備份的相同 ESXi 主機，或掛載到具有相同類型的 VM 和主機配置的備用 ESXi 主機。您可以在主機上多次掛載資料儲存。 
---
= 掛載備份
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您想存取備份中的文件，您可以從備份中掛載傳統資料儲存。您可以將備份掛載到已建立備份的相同 ESXi 主機，或掛載到具有相同類型的 VM 和主機配置的備用 ESXi 主機。您可以在主機上多次掛載資料儲存。

您無法掛載 vVol 資料儲存。

.開始之前
* 確保備用 ESXi 主機可以連接到存儲
+
如果要掛載到備用 ESXi 主機，則必須確保備用 ESXi 主機可以連接到儲存空間並具有下列條件：

+
** 與原始主機相同的 UID 和 GID
** SnapCenter Plug-in for VMware vSphere版本的虛擬設備與原始主機的相同


* 使用 iSCSI 協定時，請確保儲存系統的啟動器已對應到 ESXi 主機。使用NVMe協定時，新增控制器以將所需的子系統對應到ESXi主機。
* 清理陳舊的 LUN/命名空間
+
由於 ESXi 主機每個資料儲存只能發現一個唯一的 LUN/命名空間，因此如果發現多個 LUN/命名空間，操作將會失敗。如果您在上一個掛載作業完成之前啟動掛載操作，或手動複製 LUN/命名空間，或在卸載作業期間未從儲存中刪除克隆，則可能會發生這種情況。為了避免發現多個克隆，您應該清理存儲上所有陳舊的 LUN/命名空間。



.關於此任務
如果資料儲存所在的FabricPool的儲存層不可用，則掛載操作可能會失敗。

.步驟
. 在 VMware vSphere 用戶端捷徑頁面中選擇 *儲存*。
. 右鍵點選資料儲存並選擇*SnapCenter Plug-in for VMware vSphere*>*安裝備份*。
. 在*Mount Datastore*頁面上，選擇備份和備份位置（主位置或輔助位置），然後選擇*Finish*。
. 可選：若要驗證資料儲存是否已掛載，請執行下列操作：
+
.. 在工具列中選擇“*選單*”，然後從下拉清單中選擇“*儲存*”。
.. 左側導覽窗格在清單頂部顯示您安裝的資料儲存。
+
若要防止在複製磁碟區時建立新的快照，請關閉SnapVault磁碟區的ONTAP方案。先前存在的快照不會被刪除。




