---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflow__restore_deleted_vms.html 
keywords:  
summary: 若要使用適用於SnapCenter Plug-in for VMware vSphere對虛擬機器備份執行還原作業，必須遵循規定的 REST API 呼叫順序。 
---
= 用於復原已刪除虛擬機器的 REST API 工作流程
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要使用適用於SnapCenter Plug-in for VMware vSphere對虛擬機器備份執行還原作業，必須遵循規定的 REST API 呼叫順序。

對於每個 REST API，新增 `\https://<server>:<port>`在 REST API 的前面形成一個完整的端點。

|===
| 步 | REST API | 評論 


| 1 | 前往
`\http://<vCenter-IP>/mob` | 從 VMware 管理物件 URL 中尋找 VM UUID。記下您要還原的 VM 的 *uuid*。 


| 2 | `/4.1/vm/{uuid}/backups` | `Get VM Backups`取得指定 VM 的備份清單。傳遞步驟 1 中的 *uuid*。記下您要還原的備份的 *backupId*。 


| 3 | `/4.1/vm/backups/{backupId}/
snapshotlocations` | `Get snapshot locations`取得指定備份的快照的位置。傳遞步驟 2 中的 *backupId*。注意*snapshotLocationsList*資訊。 


| 4 | `/4.1/vm/{moref}/backups/
availableesxhosts` | `Get available ESX Hosts`取得儲存備份的主機的資訊。注意*availableEsxHostsList*訊息。 


| 5 | `/4.1/vm/{uuid}/backups/
{backupId}/restore` | `Restore VM from a backup using uuid or restore a deleted VM`恢復指定的備份。傳遞步驟 1 中的 *uuid*。傳遞步驟 2 中的 *backupId*。在 *restoreLocations* 屬性中傳遞步驟 3 和 4 中的資訊。如果虛擬機器備份是部分備份，請設定 `restartVM`參數為“false”。  *注意：*您無法還原作為範本的虛擬機器。 
|===