---
sidebar: sidebar 
permalink: scpivs44_upgrade_to_a_new_patch.html 
keywords:  
summary: 如果要升級到相同版本的新修補程序，則必須在升級或註冊之前清除 vCenter Web Server 上的SnapCenter Plug-in for VMware vSphere快取並重新啟動伺服器。 
---
= 升級到SnapCenter Plug-in for VMware vSphere的相同版本的新修補程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果要升級到相同版本的新修補程序，則必須在升級或註冊之前清除 vCenter Web Server 上的SnapCenter Plug-in for VMware vSphere快取並重新啟動伺服器。

如果未清除插件緩存，則在以下情況下，儀表板和作業監視器中不會顯示最近的作業：

* 使用 vCenter 部署了SnapCenter Plug-in for VMware vSphere，然後升級到相同版本中的修補程式。
* SnapCenter VMware 虛擬設備部署在 vCenter 1 中。後來，此SnapCenter Plug-in for VMware vSphere被註冊到新的 vCenter2。使用補丁建立了SnapCenter Plug-in for VMware vSphere的新實例，並將其註冊到 vCenter1。但是，由於 vCenter1 仍然具有來自第一個未安裝SnapCenter Plug-in for VMware vSphere的快取插件，因此需要清除快取。




== 清除快取的步驟

. 找到 `vsphere-client-serenity`資料夾，然後找到 `com.netapp.scv.client-<release-number>`資料夾並將其刪除。
+
資料夾名稱隨每個版本的發布而變化。

+
請參閱 VMware 文件以了解 `vsphere-client-serenity`您的作業系統的資料夾。

. 重新啟動 vCenter Server。
+
然後，您可以升級SnapCenter Plug-in for VMware vSphere。


