---
sidebar: sidebar 
permalink: scpivs44_post_deployment_required_operations_and_issues.html 
keywords:  
summary: 部署適用SnapCenter Plug-in for VMware vSphere後，您必須完成安裝。 
---
= 部署後所需的操作和問題
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
部署適用SnapCenter Plug-in for VMware vSphere後，您必須完成安裝。



== 部署後必要的操作

如果您是新的SnapCenter用戶，則必須先將儲存虛擬機器新增至SnapCenter ，然後才能執行任何資料保護作業。新增儲存虛擬機器時，指定管理 LIF。您也可以新增叢集並指定叢集管理 LIF。有關添加存儲的信息，請參閱link:scpivs44_add_storage_01.html["新增儲存"^]。



== 您可能遇到的部署問題

* 部署虛擬設備後，在下列情況下，儀表板上的「*備份作業*」標籤可能無法載入：
+
** 您正在執行 IPv4 位址，並且有兩個用於SnapCenter VMware vSphere 主機的 IP 位址。結果，作業請求被傳送到SnapCenter伺服器無法辨識的 IP 位址。為了防止此問題，請新增要使用的 IP 位址，如下所示：
+
... 導覽至部署適用SnapCenter Plug-in for VMware vSphere的位置： `/opt/netapp/scvservice/standalone_aegis/etc`
... 開啟檔案 network-interface.properties。
... 在 `network.interface=10.10.10.10`在欄位中，新增您想要使用的 IP 位址。


** 您有兩個 NIC。


* 部署SnapCenter Plug-in for VMware vSphere後，適用SnapCenter Plug-in for VMware vSphere的vCenter 中的 MOB 項目可能仍顯示舊版編號。當 vCenter 中正在執行其他作業時，可能會發生這種情況。 vCenter 最終會更新該條目。


若要解決這些問題，請執行以下操作：

. 清除瀏覽器緩存，然後檢查 GUI 是否正常運作。
+
如果問題仍然存在，請重新啟動 VMware vSphere 用戶端服務

. 登入 vCenter，然後在工具列中選擇 *選單*，然後選擇 *SnapCenter Plug-in for VMware vSphere*。




== 管理身份驗證錯誤

如果您不使用管理員憑證，部署SnapCenter Plug-in for VMware vSphere或移轉後可能會收到驗證錯誤。如果遇到身份驗證錯誤，則必須重新啟動服務。

.步驟
. 使用下列格式登入SnapCenter Plug-in for VMware vSphere管理 GUI `\https://<appliance-IP-address>:8080` 。使用管理員使用者名稱、密碼和 MFA 令牌詳細資料登入。可以從維護控制台產生 MFA 令牌。
. 重新啟動服務。




== 使用SnapCenter伺服器SnapCenter Plug-in for VMware vSphere

如果您想要在SnapCenter中執行基於 VMDK 的應用程式工作流程（針對虛擬化資料庫和檔案系統的基於應用程式的保護工作流程），則必須向SnapCenter伺服器SnapCenter Plug-in for VMware vSphere。

.開始之前
* 您必須執行SnapCenter Server 4.2 或更高版本。
* 您必須已部署並啟用SnapCenter Plug-in for VMware vSphere。


.關於此任務
* 您可以使用SnapCenter GUI 新增「vsphere」類型主機，並向SnapCenter伺服器SnapCenter Plug-in for VMware vSphere。
+
連接埠 8144 是預先定義的，SnapCenter Plug-in for VMware vSphere內的通訊。

+
您可以在同一SnapCenter伺服器上註冊SnapCenter Plug-in for VMware vSphere實例，以支援虛擬機器上基於應用程式的資料保護作業。您無法在多個SnapCenter伺服器上SnapCenter Plug-in for VMware vSphere。

* 對於連結模式下的 vCenter，您必須為每個 vCenterSnapCenter Plug-in for VMware vSphere。


.步驟
. 在SnapCenter GUI 左側導覽窗格中，選擇 *Hosts*。
. 驗證頂部是否選擇了“*託管主機*”選項卡，然後找到虛擬設備主機名稱並驗證它是否從SnapCenter伺服器解析。
. 選擇“*新增*”以啟動精靈。
. 在「新增主機」對話方塊中，指定要新增至SnapCenter伺服器的主機，如下表所示：
+
|===
| 對於這個領域… | 這樣做… 


| 主機類型 | 選擇 *vSphere* 作為主機類型。 


| 主機名稱 | 驗證虛擬設備的 IP 位址。 


| 憑證 | 輸入部署期間提供的SnapCenter Plug-in for VMware vSphere的使用者名稱和密碼。 
|===
. 選擇*提交*。
+
成功新增 VM 主機後，它將顯示在「受管主機」標籤上。

. 在左側導覽窗格中，選擇“*設定*”，然後選擇“*憑證*”選項卡，然後選擇“*新增*”為虛擬裝置新增憑證。
. 提供部署SnapCenter Plug-in for VMware vSphere期間指定的憑證資訊。
+

NOTE: 您必須在身份驗證欄位中選擇 Linux。



.完成後
如果修改了SnapCenter Plug-in for VMware vSphere，則必須使用SnapCenter託管主機頁面更新SnapCenter伺服器中的註冊。
