---
sidebar: sidebar 
permalink: scpivs44_restore_vmdks_from_backups.html 
keywords:  
summary: 您可以從傳統虛擬機器或 vVol 虛擬機器的主備份或輔助備份中還原現有的 VMDK 或已刪除或分離的 VMDK。 
---
= 從備份還原 VMDK
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以從傳統虛擬機器或 vVol 虛擬機器的主備份或輔助備份中還原現有的 VMDK 或已刪除或分離的 VMDK。

您可以將虛擬機器上的一個或多個虛擬機器磁碟 (VMDK) 還原到同一個資料儲存區。


TIP: 為了提高 NFS 環境中復原作業的效能，請啟用 VMware 應用程式 vStorage API for Array Integration (VAAI)。

.開始之前
* 必須存在備份。
+
您必須已使用適用於SnapCenter Plug-in for VMware vSphere建立虛擬機器的備份。

* VM 不得處於傳輸狀態。
+
您要復原的虛擬機器不能處於 vMotion 或 Storage vMotion 狀態。



.關於此任務
* 如果 VMDK 被刪除或從 VM 中分離，則還原操作會將 VMDK 附加到 VM。
* 如果虛擬機器所在的FabricPool的儲存層不可用，則復原操作可能會失敗。
* 連接和恢復操作使用預設的 SCSi 控制器連接 VMDK。但是，當備份連接到具有 NVMe 磁碟的 VM 的 VMDK 時，連接和復原作業將使用 NVMe 控制器（如果可用）。


.步驟
. 在 VMware vSphere 用戶端 GUI 中，選擇工具列中的 *選單*，然後從下拉清單中選擇 *虛擬機器和範本*。
. 在左側導覽窗格中，右鍵單擊虛擬機，然後在下拉清單中選擇“SnapCenter Plug-in for VMware vSphere”，然後在輔助下拉清單中選擇“還原”。
. 在「*還原*」精靈中的「選擇備份」頁面上，選擇要從中還原的備份副本。
+
您可以搜尋特定的備份名稱或部分備份名稱，也可以透過選擇篩選器圖示並選擇日期和時間範圍來過濾備份列表，選擇是否需要包含 VMware 快照的備份、是否需要已安裝的備份以及主要位置或次要位置。選擇“*確定*”返回精靈。

. 在「選擇範圍」頁面上，選擇恢復目標。
+
|===
| 恢復至… | 指定還原目標... 


| 原始資料存儲 | 從下拉清單中選擇*特定磁碟*，然後選擇*下一步*。在資料儲存選擇表中，您可以選擇或取消選擇任何 VMDK。 


| 備用位置的備用資料存儲 | 選擇目標資料儲存並從清單中選擇不同的資料儲存。 
|===
. 在「選擇位置」頁面上，選擇要復原的快照（主快照或輔助快照）。
. 查看摘要頁面，然後選擇*完成*。
. 可選：透過選擇螢幕底部的「最近任務」來監控操作進度。
. 刷新螢幕以顯示更新的資訊。

