---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_overview.html 
keywords:  
summary: '您可以從 Windows 用戶作業系統上的虛擬機器磁碟 (VMDK) 還原檔案或資料夾。' 
---
= 工作流程、先決條件與限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以從 Windows 用戶作業系統上的虛擬機器磁碟 (VMDK) 還原檔案或資料夾。



== 來賓還原工作流程

客戶作業系統還原操作包含以下步驟：

. 附
+
將虛擬磁碟附加到客戶虛擬機器或代理虛擬機器並啟動客戶檔案復原會話。

. 等待
+
等待附加操作完成後，您才可以瀏覽和恢復。當附加

+
操作完成後，將自動建立訪客文件恢復會話，並發送電子郵件通知

+
發送。

. 選擇檔案或資料夾
+
在用戶端檔案還原工作階段中瀏覽 VMDK 並選擇要還原的一個或多個檔案或資料夾。

. 恢復
+
將選定的檔案或資料夾還原到指定位置。





== 恢復訪客文件和資料夾的先決條件

在從 Windows 用戶作業系統上的 VMDK 還原一個或多個檔案或資料夾之前，您必須了解所有要求。

* 必須安裝並執行 VMware 工具。
+
SnapCenter使用來自 VMware 工具的資訊與 VMware Guest OS 建立連線。

* Windows 客戶作業系統必須執行 Windows Server 2008 R2 或更高版本。
+
有關受支援版本的最新信息，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp互通性矩陣工具 (IMT)"^]。

* 目標 VM 的憑證必須指定內建網域管理員帳戶或內建本機管理員帳戶。使用者名稱必須是“管理員”。在開始復原作業之前，必須為要附加虛擬磁碟的 VM 配置憑證。附加操作和後續恢復操作都需要憑證。工作群組使用者可以使用內建的本機管理員帳戶。
+

IMPORTANT: 如果您必須使用非內建管理員帳戶但在 VM 內具有管理權限的帳戶，則必須在來賓 VM 上停用 UAC。

* 您必須知道要從中還原的備份快照和 VMDK。
+
SnapCenter Plug-in for VMware vSphere不支援搜尋要還原的檔案或資料夾。因此，在開始之前，您必須知道相對於快照和對應 VMDK 的檔案或資料夾的位置。

* 要附加的虛擬磁碟必須位於SnapCenter備份中。
+
包含要還原的檔案或資料夾的虛擬磁碟必須位於使用適用於SnapCenter Plug-in for VMware vSphere虛擬設備執行的 VM 備份中。

* 若要使用代理虛擬機，必須配置代理虛擬機。
+
如果要將虛擬磁碟附加到代理虛擬機，則必須在附加和復原作業開始之前設定代理虛擬機器。

* 對於名稱非英文字母的文件，您必須將它們恢復到目錄中，而不是單一文件。
+
您可以透過恢復文件所在的目錄來恢復具有非字母名稱的文件，例如日語漢字。

* 不支援從 Linux 客戶作業系統恢復
+
您無法從執行 Linux 客戶作業系統的 VM 還原檔案和資料夾。但是，您可以附加 VMDK，然後手動恢復檔案和資料夾。有關受支援的客戶作業系統的最新信息，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp互通性矩陣工具 (IMT)"^]。





== 來賓檔案還原限制

從客戶作業系統還原檔案或資料夾之前，您應該了解該功能不支援哪些功能。

* 您無法在來賓作業系統內還原動態磁碟類型。
* 如果還原加密的檔案或資料夾，則不會保留加密屬性。您無法將檔案或資料夾還原到加密資料夾。
* 訪客文件瀏覽頁面顯示隱藏的文件和資料夾，您無法過濾。
* 您無法從 Linux 客戶作業系統復原。
+
您無法從執行 Linux 客戶作業系統的 VM 還原檔案和資料夾。但是，您可以附加 VMDK，然後手動恢復檔案和資料夾。有關受支援的客戶作業系統的最新信息，請參閱 https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp互通性矩陣工具 (IMT)"^]。

* 您無法從 NTFS 檔案系統還原到 FAT 檔案系統。
+
當您嘗試從 NTFS 格式還原為 FAT 格式時，不會複製 NTFS 安全性描述符，因為 FAT 檔案系統不支援 Windows 安全性屬性。

* 您無法從克隆的 VMDK 或未初始化的 VMDK 恢復客戶檔案。
* 您無法復原檔案的目錄結構。
+
如果選擇恢復嵌套目錄中的文件，則不會使用相同的目錄結構來恢復該文件。目錄樹沒有恢復，只有檔案。如果要還原目錄樹，您可以複製結構頂部的目錄本身。

* 您無法將客戶檔案從 vVol VM 還原到備用主機。
* 您無法恢復加密的訪客檔案。

