---
sidebar: sidebar 
permalink: scpivs44_ontap_rbac_features_in_snapcenter.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere可與 vCenter Server RBAC、 SnapCenter RBAC（需要支援基於應用程式的操作時）和ONTAP RBAC 搭配使用，以確定特定使用者可以在特定儲存系統上的物件上執行哪些SnapCenter任務。 
---
= SnapCenter Plug-in for VMware vSphere）中的ONTAP RBAC 功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/



NOTE: ONTAP RBAC 僅適用於SnapCenter Server 應用程式一致性（透過 VMDK 的應用程式）作業。

[role="lead"]
ONTAP基於角色的存取控制 (RBAC) 可讓您控制對特定儲存系統的存取以及使用者可以在這些儲存系統上執行的操作。SnapCenter Plug-in for VMware vSphere可與 vCenter Server RBAC、 SnapCenter RBAC（需要支援基於應用程式的操作時）和ONTAP RBAC 搭配使用，以確定特定使用者可以在特定儲存系統上的物件上執行哪些SnapCenter任務。

SnapCenter使用您設定的憑證（使用者名稱和密碼）來驗證每個儲存系統並確定可以在該儲存系統上執行哪些操作。SnapCenter Plug-in for VMware vSphere對每個儲存系統使用一組憑證。這些憑證決定了可以在該儲存系統上執行的所有任務；換句話說，這些憑證適用於SnapCenter，而不是單一SnapCenter用戶。

ONTAP RBAC 僅適用於存取儲存系統和執行與儲存相關的SnapCenter任務，例如備份虛擬機器。如果您沒有特定儲存系統的適當ONTAP RBAC 權限，則無法對該儲存系統上託管的 vSphere 物件執行任何任務。

每個儲存系統都有一組與其關聯的ONTAP權限。

同時使用ONTAP RBAC 和 vCenter Server RBAC 可帶來以下好處：

* 安全
+
管理員可以控制哪些使用者可以在細粒度的 vCenter Server 物件層級和儲存系統層級執行哪些任務。

* 審計資訊
+
在許多情況下， SnapCenter在儲存系統上提供審計跟踪，讓您可以將事件追溯到執行儲存修改的 vCenter 用戶。

* 可用性
+
您可以在一個地方維護控制器憑證。


