---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflow__restore_vmdks.html 
keywords:  
summary: 若要使用適用於SnapCenter Plug-in for VMware vSphere對 VMDK 執行還原操作，必須遵循規定的 REST API 呼叫順序。 
---
= 用於恢復 VMDK 的 REST API 工作流程
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
若要使用適用於SnapCenter Plug-in for VMware vSphere對 VMDK 執行還原操作，必須遵循規定的 REST API 呼叫順序。

對於每個 REST API，新增 `\https://<server>:<port>`在 REST API 的前面形成一個完整的端點。

|===
| 步 | REST API | 評論 


| 1 | 前往 `\http://<vCenter-IP>/mob` | 從 VMware 管理物件 URL 中尋找 VM moref。注意 VMDK 所在 VM 的 *moref*。 


| 2 | `/4.1/vm/{moref}/backups` | `Get VM Backups`取得指定 VM 的備份清單。傳遞步驟 1 中的 *moref*。記下您要還原的備份的 *backupId*。 


| 3 | `/4.1/vm/backups/{backupId}/
snapshotlocations` | `Get snapshot locations`取得指定備份的快照的位置。傳遞步驟 2 中的 *backupId*。注意*snapshotLocationsList*資訊。 


| 4 | `/4.1/vm/{moref}/backups/
vmdklocations` | `Get Vmdk Locations`取得指定 VM 的 VMDK 清單。注意*vmdkLocationsList*資訊。 


| 5 | `/4.1/vm/{ moref}/backups/
{backupId}/
availabledatastores` | `Get Available Datastores`取得可用於復原操作的資料儲存清單。傳遞步驟 1 中的 *moref*。傳遞步驟 2 中的 *backupId*。注意*DatastoreNameList*資訊。 


| 6 | `/4.1/vm/{moref}/backups/
availableesxhosts` | `Get available ESX Hosts`取得儲存備份的主機的資訊。傳遞步驟 1 中的 *moref*。注意*availableEsxHostsList*訊息。 


| 7 | `/4.1/vm/{moref}/backups/
{backupId}/restorevmdks`  a| 
`Restore a VMDK from a backup`從指定的備份還原指定的 VMDK。在 *esxHost* 屬性中，傳遞步驟 6 中 *availableEsxHostsList* 的訊息。將步驟 3 至 5 的資訊傳遞給 *vmdkRestoreLocations* 屬性：

* 在 restoreFromLocation 屬性中，傳遞步驟 3 中來自 snapshotLocationsList 的資訊。
* 在 vmdkToRestore 屬性中，傳遞步驟 4 中 vmdkLocationsList 中的資訊。
* 在 restoreToDatastore 屬性中，傳遞步驟 5 中 DatastoreNameList 中的資訊。


|===