---
sidebar: sidebar 
permalink: scpivs44_predefined_roles_packaged_with_snapcenter.html 
keywords:  
summary: 為了簡化使用 vCenter Server RBAC 的操作，SnapCenter Plug-in for VMware vSphere提供了一組預先定義角色，使用戶能夠執行SnapCenter任務。還有一個唯讀角色，允許使用者查看SnapCenter訊息，但不能執行任何任務。 
---
= SnapCenter Plug-in for VMware vSphere隨附的預先定義角色
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
為了簡化使用 vCenter Server RBAC 的操作，SnapCenter Plug-in for VMware vSphere提供了一組預先定義角色，使用戶能夠執行SnapCenter任務。還有一個唯讀角色，允許使用者查看SnapCenter訊息，但不能執行任何任務。

預先定義角色既具有所需的SnapCenter特定權限，也具有本機 vCenter Server 權限，以確保任務正確完成。此外，角色設定為在所有支援的 vCenter Server 版本中擁有必要的權限。

作為管理員，您可以將這些角色指派給適當的使用者。

每次重新啟動 vCenter Web 用戶端服務或修改安裝時，SnapCenter Plug-in for VMware vSphere將這些角色還原為其預設值（初始權限集）。如果升級SnapCenter Plug-in for VMware vSphere，則預先定義角色將自動升級以與該版本的插件一起使用。

您可以透過選擇「選單」>「管理」>「角色」在 vCenter GUI 中查看預先定義的角色，如下表所示。

|===
| 角色 | 描述 


| SCV 管理員 | 提供執行所有適用SnapCenter Plug-in for VMware vSphere任務所需的所有本機 vCenter Server 和SnapCenter特定權限。從 SCV 6.1 版本開始，該角色新增了建立二級保護的新權限。 


| SCV備份 | 提供備份 vSphere 物件（虛擬機器和資料儲存區）所需的所有本機 vCenter Server 和SnapCenter特定權限。用戶還具有配置權限。用戶無法恢復備份。從 SCV 6.1 版本開始，該角色新增了建立二級保護的新權限。 


| SCV 來賓文件還原 | 提供還原客戶檔案和資料夾所需的所有本機 vCenter Server 和SnapCenter特定權限。使用者無法恢復虛擬機器或 VMDK。 


| SCV恢復 | 提供還原使用適用於SnapCenter Plug-in for VMware vSphere的vSphere 物件以及還原來賓檔案和資料夾所需的所有本機 vCenter Server 和SnapCenter特定權限。用戶還具有配置權限。使用者無法備份 vSphere 物件。 


| SCV 視圖 | 提供SnapCenter Plug-in for VMware vSphere的唯讀存取權。 
|===