---
sidebar: sidebar 
permalink: scpivs44_restore_vms_from_backups.html 
keywords:  
summary: 還原虛擬機器時，您可以使用所選的備份副本覆寫現有內容，也可以複製虛擬機器。 
---
= 從備份還原虛擬機
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
還原虛擬機器時，您可以使用所選的備份副本覆寫現有內容，也可以複製虛擬機器。

您可以將虛擬機器還原到以下位置：

* 恢復到原始位置
+
** 到原始 ESXi 主機上掛載的原始資料儲存（這將覆蓋原始虛擬機器）


* 恢復至備用位置
+
** 到原始 ESXi 主機上掛載的其他資料存儲
** 到由同一 vCenter 管理的不同 ESXi 主機上掛載的原始資料儲存區
** 到由同一 vCenter 管理的不同 ESXi 主機上掛載的不同資料儲存區
** 到由連結模式下的不同 vCenter 管理的不同 ESXi 主機上掛載的不同資料儲存區





NOTE: 您無法將 vVol VM 還原到備用主機。


NOTE: 不支援以下復原工作流程：新增儲存虛擬機，然後執行該虛擬機的備份，然後刪除儲存虛擬機並新增包含相同儲存虛擬機的集群，然後嘗試還原原始備份。


TIP: 為了提高 NFS 環境中復原作業的效能，請啟用 VMware 應用程式 vStorage API for Array Integration (VAAI)。

.開始之前
* 必須存在備份。
+
您必須先使用適用於SnapCenter Plug-in for VMware vSphere建立虛擬機器的備份，然後才能還原虛擬機器。

+

NOTE: 如果有由SnapCenter Plug-in for VMware vSphere以外的軟體執行的虛擬機器快照，則還原作業無法成功完成。

* 目標資料儲存必須準備就緒。
+
** 還原作業的目標資料儲存必須有足夠的空間來容納所有 VM 檔案的副本（例如：vmdk、vmx、vmsd）。
** 目標資料儲存區不得包含先前還原作業失敗而留下的陳舊虛擬機器檔案。陳舊的文件具有名稱格式 `restore_xxx_xxxxxx_<filename>`。


* VM 不得處於傳輸狀態。
+
您要復原的虛擬機器不能處於 vMotion 或 Storage vMotion 狀態。

* HA 配置錯誤
+
將備份還原到其他位置之前，請確保 vCenter ESXi 主機摘要畫面上沒有顯示 HA 設定錯誤。

* 恢復到不同位置
+
** 還原到其他位置時，SnapCenter Plug-in for VMware vSphere必須在作為還原作業目標的 vCenter 中執行。目標資料儲存必須具有足夠的空間。
** 「還原到備用位置」欄位中的目標 vCenter 必須是 DNS 可解析的。




.關於此任務
* VM 已取消註冊並重新註冊
+
虛擬機的還原作業會取消註冊原始虛擬機，從備份快照還原虛擬機，然後在同一 ESXi 伺服器上以相同的名稱和設定註冊還原的虛擬機。恢復後，您必須手動將虛擬機器新增至資源組。

* 恢復資料存儲
+
您無法恢復資料存儲，但可以還原資料儲存中的任何虛擬機器。

* 恢復 vVol 虛擬機
+
** 不支援跨虛擬機器的 vVol 資料儲存。由於跨 VM 的 vVol 資料儲存中附加的 VMDK 未備份，因此復原的 VM 將僅包含部分 VMDK。
** 您無法將 vVol 還原到備用主機。
** 不支援 vVol 自動重新平衡。


* 虛擬機器的 VMware 一致性快照失敗
+
即使虛擬機器的 VMware 一致性快照失敗，虛擬機器仍會備份。您可以在還原精靈中檢視備份副本中包含的實體並將其用於還原作業。

* 如果虛擬機器所在的FabricPool的儲存層不可用，則復原操作可能會失敗。


.步驟
. 在 VMware vSphere 用戶端 GUI 中，選擇工具列中的 *選單*，然後從下拉清單中選擇 *虛擬機器和範本*。
+

NOTE: 如果要還原已刪除的虛擬機，則必須將新增至SnapCenter Plug-in for VMware vSphere的儲存虛擬機器憑證 `vsadmin`或具有與 `vsadmin`。

. 在左側導覽窗格中，以滑鼠右鍵按一下虛擬機，然後在下拉清單中選擇“* SnapCenter Plug SnapCenter Plug-in for VMware vSphere*”，然後在輔助下拉清單中選擇“* 還原 *”以啟動精靈。
. 在*還原*精靈的*選擇備份*頁面上，選擇要還原的備份快照。
+
您可以搜尋特定的備份名稱或部分備份名稱，也可以透過選擇篩選器圖示並選擇日期和時間範圍來過濾備份列表，選擇是否需要包含 VMware 快照的備份、是否需要已掛載的備份以及位置。選擇“*確定*”返回精靈。

. 在*選擇範圍*頁面上，在*復原範圍*欄位中選擇*整個虛擬機器*，然後選擇復原位置，然後輸入應掛載備份的目標資訊。
+
在 *VM 名稱* 欄位中，如果存在相同的 VM 名稱，則新的 VM 名稱格式為 `<vm_name>_<timestamp>`。

+
還原部分備份時，復原作業會跳過「選擇範圍」頁面。

. 在「選擇位置」頁面上，選擇復原的資料儲存的位置。
+
在SnapCenter Plug-in for VMware vSphere中，您可以為FlexGroup磁碟區選擇二級儲存。

. 查看摘要頁面，然後選擇*完成*。
. 可選：透過選擇螢幕底部的「最近任務」來監控操作進度。
+
刷新螢幕以顯示更新的資訊。



.完成後
* 更改 IP 位址
+
如果您還原到其他位置，則必須變更新建立的 VM 的 IP 位址，以避免在設定靜態 IP 位址時發生 IP 位址衝突。

* 將還原的虛擬機器新增至資源組
+
儘管虛擬機器已恢復，但它們不會自動添加到其先前的資源組中。因此，您必須手動將復原的虛擬機器新增至適當的資源群組。


